void owInit();
void SetSpeed(int standard);
int OWTouchReset(void);
void OWWriteBit(int bit);
int OWReadBit(void);
void OWWriteByte(int data);
int OWReadByte(void);
int OWTouchByte(int data);
void OWBlock(unsigned char *data, int data_len);
int OWOverdriveSkip(unsigned char *data, int data_len);
